# Generated by Django 5.2 on 2025-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='direction',
            field=models.CharField(choices=[('Centro', 'Centro'), ('Norte', 'Norte'), ('Sul', 'Sul'), ('Leste', 'Leste'), ('Oeste', 'Oeste'), ('Nordeste', 'Nordeste'), ('Noroeste', 'Noroeste'), ('Sudeste', 'Sudeste'), ('Sudoeste', 'Sudoeste')], default='Centro', max_length=10),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='joystick_x',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='joystick_y',
            field=models.IntegerField(default=2000),
        ),
    ]
