# Generated by Django 5.2 on 2025-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermonitor', '0002_serverstatus_direction_serverstatus_joystick_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('data_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
